spring.application.name=leetcode-service

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/leetcodedb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:leetcodeuser}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:leetcodepass}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
