ALTER TABLE users ADD COLUMN IF NOT EXISTS role VARCHAR(32);
UPDATE users SET role = 'USER' WHERE role IS NULL OR role = '';
ALTER TABLE users ALTER COLUMN role SET DEFAULT 'USER';
ALTER TABLE users ALTER COLUMN role SET NOT NULL;
ALTER TABLE users DROP CONSTRAINT IF EXISTS ck_users_role;
ALTER TABLE users ADD CONSTRAINT ck_users_role CHECK (role IN ('USER', 'ADMIN'));
