spring.application.name=booking-service

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bookingsdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:bookingsuser}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:bookingspass}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
