spring.application.name=media-service

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/mediadb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:mediauser}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:mediapass}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=false

spring.servlet.multipart.max-file-size=${SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE:120MB}
spring.servlet.multipart.max-request-size=${SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE:120MB}
