spring.application.name=whatsapp-service

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/chatsdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:chatsuser}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:chatspass}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
